arc:
  ai:
    face:
      appid: 296RDaHNnwQwtXuLhLB1SXwiFLDaLwNXudz4zjiipQoS
      sdk-key: 3VDbPvtymYVXDasJ97GR8eLX4fcDRZ3i1XM9nKEJrrKz
      active-file-path: C:\Users\dingchao\Downloads\86L111BR413VLJHN.dat
      lib-path: C:\visheeWork\svn\facedemo4.0\libs\WIN64
      active-key: 86L1-11BR-413V-LJHN
      os: WINDOWS
      arc: 64
spring:
  datasource:
    url: jdbc:mysql://139.224.24.254:5688/arcface_test?characterEncoding=UTF-8
    username: ccrttest
    password: CcrtIItest@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 1800000
      minimum-idle: 5



mybatis:
  mapper-locations: classpath*:mapping/*.xml
logging:
  level:
    com.vishee.arcface: debug

pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  offset-as-page-num: true
  row-bounds-with-count: true